
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer
ot_ele=[]

def name_search(name=""):
    from pathlib import Path
    import webbrowser
    import pandas as pd
    # from tkinter import *
    # Explicit imports to satisfy Flake8
    from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


    OUTPUT_PATH = Path(__file__).parent
    ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\Akshat\OneDrive\Desktop\chatbot dc\main\assets")


    # name="oneplus"
    def relative_to_assets(path: str) -> Path:
        return ASSETS_PATH / Path(path)


    window = Tk()
    # window.geometry("1200x768")
    window.configure(bg = "#FFFFFF")
    # window.eval('tk::PlaceWindow . center')
    w=window.winfo_screenwidth()
    h=window.winfo_screenheight()
    x=w/2 -600
    y=h/2-440
    window.geometry(f"1200x768+{int(x)}+{int(y)}")
    canvas = Canvas(
        window,
        bg = "#FFFFFF",
        height = 768,
        width = 1200,
        bd = 0,
        highlightthickness = 0,
        relief = "ridge"
    )
    def enter(tag):
        canvas.config(cursor="hand2")

    def leave(tag):
        canvas.config(cursor="")
    def on_c(link,event):
        webbrowser.open_new(link) 
    def display(user):
        global ot_ele
        for i in ot_ele:
            canvas.delete(i)
        ot_ele=[]
        print(user)
        df=pd.read_csv("final.csv")
        # df['name']=df['name'].str.lower()
        user=user.lower()
        df=df[df['name'].str.lower().str.contains(user)]
        l=min(len(df),5)
        if(l==0):
            return 0
        for i in range(l):
            rec=df.iloc[i]
            # canvas.create_rectangle()
            r1=canvas.create_rectangle(
                40.0,
                311.0+i*85,
                396.0,
                396.0+i*85,
                fill="#D9D9D9",
                outline=""
            )
            t1=canvas.create_text(
                50.0,
                323.0+i*85,
                anchor="nw",
                text=rec['name'],
                fill="#000000",
                font=("Inter", 20 * -1)
            )

            r2=canvas.create_rectangle(
                396.0,
                311.0+i*85,
                550.0,
                396.0+i*85,
                fill="#D9D9D9",
                outline="")

            r3=canvas.create_rectangle(
                550.0,
                311.0+i*85,
                893.0,
                396.0+i*85,
                fill="#D9D9D9",
                outline="")

            t2=canvas.create_text(
                676.0,
                323.0+i*85,
                anchor="nw",
                text=rec['price'],
                fill="#000000",
                font=("Inter", 25 * -1)
            )

            r4=canvas.create_rectangle(
                893.0,
                311.0+i*85,
                1160.0,
                396.0+i*85,
                fill="#D9D9D9",
                outline="")

            link=canvas.create_text(
                916.0,
                323.0+i*85,
                anchor="nw",
                text="Click to Buy",
                fill="#000000",
                font=("Inter", 25 * -1)
            )
            canvas.tag_bind(link, '<Enter>', enter)
            canvas.tag_bind(link, '<Leave>', leave)
            canvas.tag_bind(link,'<ButtonPress-1>',lambda event,link=rec['link'] : on_c(link,event))
            t3=canvas.create_text(
                457.0,
                323.0+i*85,
                anchor="nw",
                text=rec['ratings'],
                fill="#000000",
                font=("Inter", 25 * -1)
            )
            ot_ele=ot_ele+[r1,r2,r3,r4,t1,t2,t3,link]
    
    canvas.place(x = 0, y = 0)
    image_image_1 = PhotoImage(
        file=relative_to_assets("bg_name.png"))
    image_1 = canvas.create_image(
        600.0,
        384.0,
        image=image_image_1
    )

    canvas.create_text(
        46.0,
        36.0,
        anchor="nw",
        text="search again : ",
        fill="#000000",
        font=("verdana",20)
    )

    entry_image_1 = PhotoImage(
        file=relative_to_assets("entry_n.png"))
    entry_bg_1 = canvas.create_image(
        553.5,
        66.5,
        image=entry_image_1
    )
    entry_1 = Entry(
        bd=0,
        bg="#C4F7FF",
        fg="#000716",
        font=("verdana",12),
        highlightthickness=0
    )
    entry_1.place(
        x=392.0,
        y=36.0,
        width=323.0,
        height=59.0
    )
    recent=canvas.create_text(
        46.0,
        134.0,
        anchor="nw",
        text=f"recent search : {name}",
        fill="#000000",
        font=("Inter", 20)
    )
    def sbyname(temp,recent):
        # recent
        name=entry_1.get()
        # window.destroy()
        canvas.itemconfig(recent,text=f"recent search : {name}")
        display(name)
    entry_1.bind("<Return>",lambda x:sbyname(x,recent))

    image_image_2 = PhotoImage(
        file=relative_to_assets("col_grad.png"))
    image_2 = canvas.create_image(
        600.0,
        266.0,
        image=image_image_2
    )

    canvas.create_text(
        67.0,
        236.0,
        anchor="nw",
        text="Name               Rating       Price          Link to Buy",
        fill="#FFFFFF",
        font=("Inter",50*-1)
    )
    display(name)

    window.resizable(False, False)
    window.mainloop()
